/**
 * BPMN DI (Diagram Interchange) Optimizer
 * Simplifies BPMN visual layout to reduce token usage while maintaining validity
 */

/**
 * Simplify waypoints in BPMN edges to use only start and end points
 */
function simplifyWaypoints(xml: string): string {
    // Match BPMNEdge blocks with multiple waypoints
    const edgePattern = /(<bpmndi:BPMNEdge[^>]*>)([\s\S]*?)(<\/bpmndi:BPMNEdge>)/g;

    return xml.replace(edgePattern, (match, openTag, content, closeTag) => {
        // Extract all waypoints
        const waypoints = content.match(/<di:waypoint[^>]*\/>/g) || [];

        // If more than 2 waypoints, keep only first and last
        if (waypoints.length > 2) {
            const simplified = `${openTag}\n        ${waypoints[0]}\n        ${waypoints[waypoints.length - 1]}\n      ${closeTag}`;
            return simplified;
        }

        return match;
    });
}

/**
 * Remove BPMNLabel elements to reduce size (labels are optional in BPMN DI)
 */
function removeLabels(xml: string): string {
    // Remove BPMNLabel blocks (they're optional for rendering)
    return xml.replace(/<bpmndi:BPMNLabel[^>]*>[\s\S]*?<\/bpmndi:BPMNLabel>/g, '');
}

/**
 * Simplify coordinates to grid-aligned values (multiples of 10)
 */
function simplifyCoordinates(xml: string): string {
    // Round all x and y coordinates to nearest 10
    return xml.replace(/([xy])="(\d+(?:\.\d+)?)"/g, (match, axis, value) => {
        const rounded = Math.round(parseFloat(value) / 10) * 10;
        return `${axis}="${rounded}"`;
    });
}

/**
 * Remove empty lane flowNodeRef elements (they're being generated incorrectly anyway)
 */
function removeEmptyFlowNodeRefs(xml: string): string {
    // Remove lanes with only whitespace in flowNodeRef
    return xml.replace(/<bpmn:lane[^>]*>\s*<\/bpmn:lane>/g, (match) => {
        // Keep the lane tag but remove empty content
        return match.replace(/>\s*</, '><');
    });
}

/**
 * Optimize BPMN DI section to reduce token usage
 * @param xml - Original BPMN XML
 * @param aggressive - If true, remove labels and simplify more aggressively
 * @returns Optimized BPMN XML
 */
export function optimizeBpmnDI(xml: string, aggressive: boolean = false): string {
    let optimized = xml;

    // Always apply these optimizations
    optimized = simplifyWaypoints(optimized);
    optimized = simplifyCoordinates(optimized);
    optimized = removeEmptyFlowNodeRefs(optimized);

    // Aggressive mode: remove labels (they'll be auto-generated by BPMN.io)
    if (aggressive) {
        optimized = removeLabels(optimized);
    }

    return optimized;
}

/**
 * Calculate approximate token count for BPMN XML
 * (rough estimate: 1 token ≈ 4 characters)
 */
export function estimateTokenCount(xml: string): number {
    return Math.ceil(xml.length / 4);
}

/**
 * Check if BPMN DI optimization is needed
 */
export function needsDIOptimization(xml: string, maxTokens: number): boolean {
    const estimatedTokens = estimateTokenCount(xml);
    return estimatedTokens > maxTokens * 0.9; // Optimize if using >90% of budget
}
