AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ProssMind Lambda Functions

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 300
    MemorySize: 1024
    Environment:
      Variables:
        SUPABASE_URL: !Ref SupabaseUrl
        SUPABASE_SERVICE_ROLE_KEY: !Ref SupabaseServiceRoleKey
        GOOGLE_API_KEY_SECRET_NAME: !Ref GoogleApiKeySecretName
        NODE_ENV: production
    Architectures:
      - arm64

Parameters:
  SupabaseUrl:
    Type: String
    Description: Supabase URL
    Default: https://lnxbvkcggoyfmpfthhhk.supabase.co
  SupabaseServiceRoleKey:
    Type: String
    NoEcho: true
    Description: Supabase Service Role Key (optional - used for logging, caching, and analytics)
    Default: ""
  AwsRegion:
    Type: String
    Description: AWS Region for deployment
    Default: us-east-1
    AllowedValues:
      - us-east-1      # US East (N. Virginia)
      - eu-central-2  # Zurich, Switzerland
      - eu-central-1  # Frankfurt, Germany (alternative)
      - eu-west-1     # Ireland (alternative)
  GoogleApiKeySecretName:
    Type: String
    Description: Name of the AWS Secrets Manager secret containing the Google API Key
    Default: "prossmind/google-api-key"

Resources:
  # BPMN Generation Functions
  GenerateBpmnFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-generate-bpmn
      CodeUri: lambda/generate-bpmn/
      Handler: dist/generate-bpmn/index.handler
      Description: Generate BPMN diagrams from text prompts
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleApiKeySecretName}*'
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:prossmind-process-bpmn-job'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /generate-bpmn
            Method: post
            RestApiId: !Ref ProssMindApi

  GenerateBpmnCombinedFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-generate-bpmn-combined
      CodeUri: lambda/generate-bpmn-combined/
      Handler: dist/generate-bpmn-combined/index.handler
      Description: Generate combined BPMN diagrams
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /generate-bpmn-combined
            Method: post
            RestApiId: !Ref ProssMindApi
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleApiKeySecretName}*'

  RefineBpmnFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-refine-bpmn
      CodeUri: lambda/refine-bpmn/
      Handler: dist/refine-bpmn/index.handler
      Description: Refine existing BPMN diagrams
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /refine-bpmn
            Method: post
            RestApiId: !Ref ProssMindApi
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleApiKeySecretName}*'

  ProcessBpmnJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-process-bpmn-job
      CodeUri: lambda/process-bpmn-job/
      Handler: dist/process-bpmn-job/index.handler
      Description: Process BPMN generation jobs asynchronously
      Timeout: 900
      MemorySize: 2048
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleApiKeySecretName}*'

  # Document Analysis Functions
  AnalyzeDocumentToBpmnFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-analyze-document-to-bpmn
      CodeUri: lambda/analyze-document-to-bpmn/
      Handler: dist/analyze-document-to-bpmn/index.handler
      Description: Analyze documents and generate BPMN
      Timeout: 600
      MemorySize: 2048
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /analyze-document-to-bpmn
            Method: post
            RestApiId: !Ref ProssMindApi
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleApiKeySecretName}*'

  VisionToBpmnFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-vision-to-bpmn
      CodeUri: lambda/vision-to-bpmn/
      Handler: dist/vision-to-bpmn/index.handler
      Description: Convert images to BPMN diagrams
      Timeout: 600
      MemorySize: 2048
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /vision-to-bpmn
            Method: post
            RestApiId: !Ref ProssMindApi
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleApiKeySecretName}*'

  ScreenRecordingToBpmnFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-screen-recording-to-bpmn
      CodeUri: lambda/screen-recording-to-bpmn/
      Handler: dist/screen-recording-to-bpmn/index.handler
      Description: Convert screen recordings to BPMN
      Timeout: 900
      MemorySize: 3008
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /screen-recording-to-bpmn
            Method: post
            RestApiId: !Ref ProssMindApi

  SpeechToTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-speech-to-text
      CodeUri: lambda/speech-to-text/
      Handler: dist/speech-to-text/index.handler
      Description: Convert speech to text
      Timeout: 600
      MemorySize: 2048
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /speech-to-text
            Method: post
            RestApiId: !Ref ProssMindApi
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleApiKeySecretName}*'

  # DMN Functions
  GenerateDmnFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-generate-dmn
      CodeUri: lambda/generate-dmn/
      Handler: dist/generate-dmn/index.handler
      Description: Generate DMN decision tables
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /generate-dmn
            Method: post
            RestApiId: !Ref ProssMindApi
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleApiKeySecretName}*'

  RefineDmnFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-refine-dmn
      CodeUri: lambda/refine-dmn/
      Handler: dist/refine-dmn/index.handler
      Description: Refine DMN decision tables
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /refine-dmn
            Method: post
            RestApiId: !Ref ProssMindApi
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleApiKeySecretName}*'

  # Dashboard & Analytics Functions
  BpmnDashboardApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-bpmn-dashboard-api
      CodeUri: lambda/bpmn-dashboard-api/
      Handler: dist/bpmn-dashboard-api/index.handler
      Description: BPMN dashboard API
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /bpmn-dashboard
            Method: get
            RestApiId: !Ref ProssMindApi

  BottleneckMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-bottleneck-metrics
      CodeUri: lambda/bottleneck-metrics/
      Handler: dist/bottleneck-metrics/index.handler
      Description: Calculate bottleneck metrics
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /bottleneck-metrics
            Method: post
            RestApiId: !Ref ProssMindApi

  # Chatbot Function
  ChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-chatbot
      CodeUri: lambda/chatbot/
      Handler: dist/chatbot/index.handler
      Description: AI chatbot for ProssMind
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /chatbot
            Method: post
            RestApiId: !Ref ProssMindApi

  # Tracking Function
  TrackVisitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prossmind-track-visitor
      CodeUri: lambda/track-visitor/
      Handler: dist/track-visitor/index.handler
      Description: Track visitor analytics
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /track-visitor
            Method: post
            RestApiId: !Ref ProssMindApi

  # API Gateway
  ProssMindApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-client-info,apikey'"
        AllowOrigin: "'*'"
        AllowCredentials: false
      Auth:
        ApiKeyRequired: false
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-client-info,apikey'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-client-info,apikey'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"


Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ProssMindApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: ProssMindApiUrl

  GenerateBpmnFunctionArn:
    Description: Generate BPMN Function ARN
    Value: !GetAtt GenerateBpmnFunction.Arn

  GenerateBpmnCombinedFunctionArn:
    Description: Generate BPMN Combined Function ARN
    Value: !GetAtt GenerateBpmnCombinedFunction.Arn
